# Generated by Django 5.2 on 2025-05-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_complaint_complaint_id_alter_submodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
