# Generated by Django 5.2 on 2025-05-24 12:47

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_complaint_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(default=management.models.generate_complaint_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
