# Generated by Django 5.2 on 2025-05-24 12:52

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_complaint_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(default=management.models.generate_complaint_id, max_length=10, unique=True),
        ),
    ]
