# Generated by Django 5.2 on 2025-05-24 12:54

import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_complaint_complaint_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_number',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_id',
            field=models.CharField(default=management.models.generate_complaint_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
